### ISSUE TITLE
Could you share the pre-trained model?

### ISSUE THREAD

**Issue by ZiggsFizz** [recong/Boundless-in-Pytorch#2]
Could you share the pre-trained model? 
Many thanks!

**Comment by recong** [comment]
Hi, I don't have enough resource, so I cannot provide pertained model. I'm sorry.

**Comment by ZiggsFizz** [comment]
> Hi, I don't have enough resource, so I cannot provide pertained model. I'm sorry.

Thanks for your reply, I think the drive google will address your resource problem :)

**Comment by recong** [comment]
I meant I don't have enough GPUs to train the model. In the paper, they said
```
Based on the findings of [9] on the benefits of training GANs with large batch sizes, we trained on 32 cores of a Google Cloud TPUv3 Pod with batch size 256.
```

**Comment by ZiggsFizz** [comment]
> I meant I don't have enough GPUs to train the model. In the paper, they said
> 
> ```
> Based on the findings of [9] on the benefits of training GANs with large batch sizes, we trained on 32 cores of a Google Cloud TPUv3 Pod with batch size 256.
> ```

I understand, anyway, thanks for your contribution.
