### ISSUE TITLE
"RuntimeError: CUDA error: out of memory " When testing the image

### ISSUE THREAD

**Issue by ZiggsFizz** [recong/Boundless-in-Pytorch#4]
Thanks for your contribution. The network can be trained on a Geforce RTX 2080Ti GPU (12GB), however, when I tested the pre-trained model with the same resolution image (256x256), the “RuntimeError: CUDA error: out of memory” occured. I checked the GPU is available, could you please help me to solve this problem?

**Comment by ZiggsFizz** [comment]
I addressed the above issues. But here is a new problem: "RuntimeError: Given groups=1, weight of size 32 5 5 5, expected input[1, 6, 256, 256] to have 5 channels, but got 6 channels instead" occurred in "gen = generator(image_tensor)", thanks for your help!

**Comment by recong** [comment]
Thank you for your attention. 
1. Could you run train.py? or how did you check your GPU is available on torch? I recommend to check
```
import torch
print(torch.cuda.is_available())
```
returns True.

2. This error indicates input size is mismatch. I don't know what image you're testing, but I wonder are you really using RGB channel? How about check your input image format?

**Comment by ZiggsFizz** [comment]
> 
> 
> Thank you for your attention.
> 
>     1. Could you run train.py? or how did you check your GPU is available on torch? I recommend to check
> 
> 
> ```
> import torch
> print(torch.cuda.is_available())
> ```
> 
> returns True.
> 
>     1. This error indicates input size is mismatch. I don't know what image you're testing, but I wonder are you really using RGB channel? How about check your input image format?

Thank you for the quick reply. I well addressed these issues with your  suggestion.
